const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const all=window.SUITE_INSTALLATIONS||[]; let current='inicio', role='oliver', map=null, layer=null;
const fmt=n=>new Intl.NumberFormat('es-ES').format(n); const mapped=()=>all.filter(x=>Number.isFinite(+x.lat)&&Number.isFinite(+x.lng));
function net(){const on=navigator.onLine;$('#netText').textContent=on?'Conectado':'Sin conexión';$('#netDot').style.background=on?'#55bd72':'#eb5757'} addEventListener('online',net);addEventListener('offline',net);net();
function techClass(t){return (t||'').toLowerCase().includes('oliver')?'oliver':(t||'').toLowerCase().includes('bernardo')?'bernardo':''}
function shell(content){$('#main').innerHTML=content}
function go(k){current=k;$$('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.go===k));({inicio,trabajos,partes,instalaciones,mapa,gestion}[k]||inicio)()}
function hero(){return `<section class="hero"><div class="hero-row"><div><p class="eyebrow">Panel unificado · v0.3</p><h2>${role==='tecnico'?'Buenas, técnico':role==='gestion'?'Panel de gestión':'Buenas, Oliver'}</h2><p>La misma forma de trabajar, ahora bajo un mismo techo.</p></div><select class="role" id="role"><option value="oliver" ${role==='oliver'?'selected':''}>Vista Oliver</option><option value="tecnico" ${role==='tecnico'?'selected':''}>Vista técnico</option><option value="gestion" ${role==='gestion'?'selected':''}>Vista gestión</option></select></div></section>`}
function bindRole(){const e=$('#role');if(e)e.onchange=()=>{role=e.value;go(current)}}
function inicio(){const m=mapped().length,p=all.length-m; shell(hero()+`<section class="cards"><button class="metric" data-jump="trabajos"><strong>8</strong><span>Trabajos de hoy</span></button><button class="metric" data-jump="partes"><strong>${localStorage.getItem('suite_draft')?'1':'0'}</strong><span>Borradores locales</span></button><button class="metric" data-jump="instalaciones"><strong>${fmt(all.length)}</strong><span>Instalaciones</span></button><button class="metric" data-jump="mapa"><strong>${fmt(p)}</strong><span>Sin ubicar</span></button></section><section class="panel"><div class="panel-head"><div><p class="eyebrow">Estado del laboratorio</p><h3>Datos reales integrados</h3></div><span class="pill">v0.3</span></div><div class="job"><div><strong>Instalaciones y buscador</strong><p>${fmt(all.length)} fichas disponibles en esta versión.</p></div><span class="ok">Activo</span></div><div class="job"><div><strong>Mapa común</strong><p>${fmt(m)} ubicaciones visibles y ${fmt(p)} pendientes.</p></div><span class="ok">Activo</span></div><div class="job"><div><strong>Supabase</strong><p>Todavía no conectado. Esta versión no envía datos a ningún servidor.</p></div><span class="warning">Pendiente</span></div></section>`);bindRole();$$('[data-jump]').forEach(b=>b.onclick=()=>go(b.dataset.jump))}
function trabajos(){shell(hero()+`<section class="panel"><div class="panel-head"><div><p class="eyebrow">Agenda familiar</p><h3>Trabajos</h3></div><span class="pill">Demostración</span></div>${all.filter(x=>x.year==='2026').slice(-8).reverse().map(x=>`<button class="install-card" data-id="${x.id}"><strong>Instalación ${x.installation}</strong><p>${x.client}</p><p>${x.address}</p><span class="tag ${techClass(x.technician)}">${x.technician||'SIN ASIGNAR'}</span></button>`).join('')}<p class="note">En la siguiente etapa esta agenda se alimentará de trabajos asignados en Supabase. Aquí solo mostramos fichas reales como prueba de navegación.</p></section>`);bindRole();bindCards()}
function partes(){
  shell(hero()+`<section class="panel tech-module-panel">
    <div class="panel-head"><div><p class="eyebrow">Módulo técnico original</p><h3>Partes de técnicos</h3></div><span class="pill ok-pill">Integración fiel</span></div>
    <p class="note"><strong>Esta v0.3 ya no usa formularios recreados.</strong> Abre la aplicación de técnicos original dentro de la Suite, conservando su flujo, campos, cálculos, fotos, historial y guardado local.</p>
    <div class="tech-preview">
      <div class="tech-preview-icon">🔧</div>
      <div><strong>Postventa Canarias</strong><p>Instalación · Reparación · Mantenimiento · Historial</p></div>
    </div>
    <a class="primary tech-launch" href="./tecnicos/index.html">ABRIR APP DE TÉCNICOS</a>
    <div class="fidelity-list">
      <div><b>✓</b><span>Formularios originales completos, sin simplificar</span></div>
      <div><b>✓</b><span>Mismos cálculos, técnicos, horas, dietas, materiales y fotos</span></div>
      <div><b>✓</b><span>Mismo historial y generación de partes</span></div>
      <div><b>✓</b><span>Guardado local actual conservado durante esta fase</span></div>
    </div>
    <p class="note">La conexión a la base compartida se añadirá después de validar que este módulo se comporta exactamente como la app que ya conocen.</p>
  </section>`);
  bindRole();
}
function instalaciones(){shell(`<div class="searchbar"><input id="q" placeholder="Buscar ID, cliente, dirección, modelo…"><div class="filters"><select id="tf"><option value="">Todos los técnicos</option><option>OLIVER</option><option>BERNARDO</option><option>POSTVENTA</option></select><select id="lf"><option value="">Todas</option><option value="mapped">Ubicadas</option><option value="pending">Sin ubicar</option></select></div></div><div class="install-list" id="list"></div>`);const render=()=>{const q=$('#q').value.trim().toLowerCase(),t=$('#tf').value,l=$('#lf').value;let r=all.filter(x=>{const blob=[x.installation,x.client,x.address,x.model,x.clientCode].join(' ').toLowerCase();const has=Number.isFinite(+x.lat)&&Number.isFinite(+x.lng);return(!q||blob.includes(q))&&(!t||(x.technician||'').includes(t))&&(!l||(l==='mapped'?has:!has))});$('#list').innerHTML=r.slice(0,250).map(x=>{const has=Number.isFinite(+x.lat)&&Number.isFinite(+x.lng);return `<button class="install-card" data-id="${x.id}"><strong>${x.installation} · ${x.client}</strong><p>${x.address||'Sin dirección'}</p><p>${x.model||'Modelo no indicado'} · <span class="tag ${techClass(x.technician)}">${x.technician||'SIN TÉCNICO'}</span></p><span class="loc ${has?'yes':'no'}">${has?'● UBICADA':'○ SIN UBICAR'}</span></button>`}).join('')+(r.length>250?`<p class="empty">Mostrando 250 de ${fmt(r.length)} resultados. Escribe algo para afinar.</p>`:'');bindCards()};$('#q').oninput=render;$('#tf').onchange=render;$('#lf').onchange=render;render()}
function bindCards(){$$('[data-id]').forEach(b=>b.onclick=()=>showDetail(b.dataset.id))}
function showDetail(id){const x=all.find(r=>r.id===id);if(!x)return;const has=Number.isFinite(+x.lat)&&Number.isFinite(+x.lng);$('#detailBody').innerHTML=`<p class="eyebrow">Ficha única</p><h2>Instalación ${x.installation}</h2><div class="detail-row"><span>Cliente</span><b>${x.client||'—'}</b></div><div class="detail-row"><span>Dirección</span><b>${x.address||'—'}</b></div><div class="detail-row"><span>Modelo</span><b>${x.model||'—'}</b></div><div class="detail-row"><span>Técnico</span><b>${x.technician||'Sin asignar'}</b></div><div class="detail-row"><span>Teléfono</span><b>${x.phone||'—'}</b></div><div class="detail-row"><span>Ubicación</span><b>${has?`${x.lat}, ${x.lng}`:'Pendiente'}</b></div><div class="detail-row"><span>Origen coordenadas</span><b>${x.coordinateSource||'—'}</b></div>${x.comments?`<p class="note"><strong>Observaciones:</strong><br>${x.comments}</p>`:''}`;$('#detail').showModal()}
$('#detail .close').onclick=()=>$('#detail').close();
function mapa(){shell(`<div class="map-wrap"><div class="map-tools"><select id="mt"><option value="">Todos los técnicos</option><option>OLIVER</option><option>BERNARDO</option><option>POSTVENTA</option></select><select id="mi"><option value="">Todas las islas</option><option value="LAS PALMAS">Las Palmas</option><option value="TENERIFE">Santa Cruz de Tenerife</option></select></div><div id="map" class="map"></div><p class="note" id="mapNote"></p></div>`);if(!window.L){$('#map').innerHTML='<p class="empty">No se pudo cargar el mapa. El listado sigue disponible.</p>';return}map=L.map('map',{preferCanvas:true}).setView([28.3,-15.8],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);const draw=()=>{if(layer)layer.remove();layer=L.layerGroup().addTo(map);const t=$('#mt').value,prov=$('#mi').value;const r=mapped().filter(x=>(!t||(x.technician||'').includes(t))&&(!prov||(prov==='LAS PALMAS'?x.province==='LAS PALMAS':x.province!=='LAS PALMAS')));r.forEach(x=>{const c=(x.technician||'').includes('OLIVER')?'#f2994a':(x.technician||'').includes('BERNARDO')?'#9b51e0':'#2f80ed';L.circleMarker([+x.lat,+x.lng],{radius:5,color:'#fff',weight:1,fillColor:c,fillOpacity:.9}).bindPopup(`<b>${x.installation}</b><br>${x.client}<br>${x.address}`).addTo(layer)});$('#mapNote').textContent=`${fmt(r.length)} puntos visibles. Todos usan la misma forma circular; el color solo distingue técnico.`};$('#mt').onchange=draw;$('#mi').onchange=draw;draw();setTimeout(()=>map.invalidateSize(),100)}
function gestion(){shell(hero()+`<section class="panel"><div class="panel-head"><div><p class="eyebrow">Administración</p><h3>Gestión</h3></div><span class="pill">Próxima fase</span></div><div class="job"><div><strong>Ficha única de instalación</strong><p>Ya operativa en listado y mapa.</p></div><span class="ok">Lista</span></div><div class="job"><div><strong>Partes compartidos</strong><p>Necesita Supabase y usuarios.</p></div><span class="warning">Pendiente</span></div><div class="job"><div><strong>Importación automática de Excel</strong><p>Se añadirá con validación y vista previa.</p></div><span class="warning">Pendiente</span></div><p class="note">Nada de esta versión modifica las tres aplicaciones actuales ni envía datos fuera del dispositivo.</p></section>`);bindRole()}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});go('inicio');